const POSTGRES_USERNAME = 'YOUR POSTGRES USERNAME'
const POSTGRES_PASSWORD = 'YOUR POSTGRES PASSWORD'
const MONGODB_USERNAME = 'YOUR MONGODB USERNAME'
const MONGODB_PASSWORD = 'YOUR MONGODB PASSWORD'

module.exports = { POSTGRES_USERNAME, POSTGRES_PASSWORD, MONGODB_USERNAME, MONGODB_PASSWORD }