const POSTGRES_USERNAME = 'POSTGRES_USERNAME'
const POSTGRES_PASSWORD = 'POSTGRES_PASSWORD'
const MONGODB_USERNAME = 'MONGODB_USERNAME'
const MONGODB_PASSWORD = 'MONGODB_PASSWORD'

module.exports = { POSTGRES_USERNAME, POSTGRES_PASSWORD, MONGODB_USERNAME, MONGODB_PASSWORD }